CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(30) NOT NULL,
    uri VARCHAR(30) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS index_app ON hits (app);
CREATE INDEX IF NOT EXISTS index_uri ON hits (uri);
CREATE INDEX IF NOT EXISTS index_ip ON hits (ip);
CREATE INDEX IF NOT EXISTS index_created ON hits (created);